# Generated by Django 6.1.2 on 2026-10-07 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(choices=[('MS', "Men's Singles"), ('WS', "Women's Singles"), ('MD', "Men's Doubles"), ('WD', "Women's Doubles"), ('XD', 'Mixed Doubles')], max_length=2)),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1)),
            ],
            options={
                'ordering': ['season', 'tournament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(default='Klubliga', max_length=60, verbose_name='league name')),
                ('best_of', models.PositiveSmallIntegerField(choices=[(1, '1 set'), (3, 'Best of 3 sets'), (5, 'Best of 5 sets')], default=3, verbose_name='sets per match')),
                ('games_per_set', models.PositiveSmallIntegerField(default=6)),
                ('deciding_match_tiebreak', models.BooleanField(default=True, verbose_name='deciding set is a match tie-break')),
                ('match_tiebreak_points', models.PositiveSmallIntegerField(default=10, verbose_name='points in the match tie-break')),
                ('two_groups_from', models.PositiveSmallIntegerField(default=8, help_text='Number of entries in a tournament from which two groups are suggested.', verbose_name='suggest two groups from')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(choices=[('MS', "Men's Singles"), ('WS', "Women's Singles"), ('MD', "Men's Doubles"), ('WD', "Women's Doubles"), ('XD', 'Mixed Doubles')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries_as_player2', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='league.group')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='league.season')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['season', 'tournament', 'player1__last_name', 'player1__first_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='league.season'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(choices=[('MS', "Men's Singles"), ('WS', "Women's Singles"), ('MD', "Men's Doubles"), ('WD', "Women's Doubles"), ('XD', 'Mixed Doubles')], max_length=2)),
                ('stage', models.CharField(choices=[('group', 'Group'), ('semi', 'Semi-final'), ('final', 'Final')], default='group', max_length=5)),
                ('slot', models.PositiveSmallIntegerField(default=0, help_text='Knockout position (1 or 2).')),
                ('status', models.CharField(choices=[('pending', 'Open'), ('played', 'Played'), ('walkover', 'Walkover'), ('cancelled', 'Not played')], default='pending', max_length=9)),
                ('score', models.CharField(blank=True, help_text="From entry 1's perspective, e.g. 6:4 3:6 10:8", max_length=60)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('entry1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.entry')),
                ('entry2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.entry')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.group')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.entry')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.season')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['season', 'tournament', 'stage', 'group__name', 'slot', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stage', 'group')), fields=('group', 'entry1', 'entry2'), name='unique_group_pairing'), models.UniqueConstraint(condition=models.Q(('stage', 'group'), _negated=True), fields=('season', 'tournament', 'stage', 'slot'), name='unique_knockout_slot')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('season', 'tournament', 'name'), name='unique_group'),
        ),
    ]
